default_language_version:
    python: python3
repos:
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.2
    hooks:
    -   id: autoflake
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.15
    hooks:
    -   id: isort
        additional_dependencies:
        -   toml
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: python3 -m mypy
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
