name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'


jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      id: set-python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"  # be careful to update cache key accordingly

    - name: Cache pip dependencies
      uses: actions/cache@v1.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.10-pip-${{ hashFiles('**/poetry.lock') }}

    - name: Cache pre-commit dependencies
      uses: actions/cache@v1.1.2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}-${{ hashFiles('**/tox.ini') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Lint
      run: |
        tox -e lint
